name: animal_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  provider: ^6.1.5
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  audioplayers: ^6.5.0
  rxdart: ^0.28.0
  audio_video_progress_bar: ^2.0.3
  just_audio: ^0.10.4
  flutter_lints: ^6.0.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
 